### ISSUE TITLE
Roadmap: Version 2.0

### ISSUE THREAD

**Issue by non-binary** [non-binary/bumblebee#3]
Bumblebee 2.0 will be a refined variation of the Bumblebee Mac application with additional useful pieces of information in a better, more optimized, and streamlined user experience.

### Priorities for 2.0:

* Single sign on.
* Deeplinks.
* Testing.
* Performance monitoring.

### Rescheduled features:

* Optimus Prime integration.
* Slack integration upgrades.
* Accessibility upgrades.

### Milestones: 

- [ ] November 13th, 2020: A: Planning and Setup.
- [ ] December 4th, 2020: B: User Interface.
- [ ] January 1st, 2021: C: Single Sign On.
- [ ] January 15th, 2021: D: Deeplinks.
- [ ] February 5th, 2021: E: Data Source.
- [ ] February 19th, 2021: F: Performance Monitoring.
- [ ] March 12th, 2021: G: Unit/UI Testing.
- [ ] April 2nd, 2021: H: Documentation.

**Comment by non-binary** [comment]
Milestone: A: Planning and Setup.
Link: [milestone#1](#).
Deadline: November 13th, 2020.

- [ ] Epic: Setup.
  - [ ] Task: Setup repository => #1.
  - [ ] Task: Reconfigure Bitrise projects to use new Git repo.
- [ ] Epic: Getting Started Mac.
  - [ ] Task: Import starter project from old repo.
  - [ ] Task: Copy over issues related to Mac project planning.
    - Choose UI framework.
    - Choose architecture.
- [ ] Epic: Refactor Slack project.
  - [ ] Task: Combine v1 and v2 Slack projects while stating new features are coming soon.
  - [ ] Task: Tear down current deployments of BB for Slack.
  - [ ] Task: Deploy new combined version to Heroku.
- [ ] Epic: Getting Started Backend.
  - [ ] Task: Import starter project from old repo.
  - [ ] Task: Deploy Hello World application to Heroku.

**Comment by non-binary** [comment]
Milestone: B: User Interface.
Link: [milestone#2](#).
Goal: December 4th, 2020.

- [ ] Epic: Mock data structures.
  - [ ] Task: Add User and Organization data structures.
  - [ ] Task: Add App data structure.
  - [ ] Task: Add Build data structure.
  - [ ] Task: Add Zendesk data structure.
  - [ ] Task: Add Stripe data structure.
  - [ ] Task: Add Bumblebee User data structure.
  - [ ] Task: Add remaining enums and related structs for UI building.
  - [ ] Task: Add fake data for use in UI.
- [ ] Epic: Add Sidebar UI and Auth page.
  - [ ] Task: Add Auth UI.
  - [ ] Task: Apps UI.
  - [ ] Task: Add Builds UI.
  - [ ] Task: Add Zendesk UI.
  - [ ] Task: Add Stripe UI.
  - [ ] Task: Add splash page for Optimus Prime UI.
  - [ ] Task: Add Manage Access UI.
  - [ ] Task: Add splash page for Performance UI.
  - [ ] Task: Add Settings UI.
  - [ ] Task: Add Accounts UI.
- [ ] Epic: Add Accounts tab bar UI.
  - [ ] Task: Add Summary tab UI.
  - [ ] Task: Add Apps tab UI.
  - [ ] Task: Add Associations tab UI.
  - [ ] Task: Add Zendesk tab UI.
  - [ ] Task: Add Stripe tab UI.
- [ ] Epic: Test UI.
  - [ ] Task: Thoroughly test UI to confirm everything is working.
  - [ ] Task: Share build with select beta testers to click around to ensure everything is working the way it should be.
  - [ ] Task: Add UI tests.
  - [ ] Task: Add unit tests.
  - [ ] Task: Configure Bitrise to run UI and Unit tests in builds.

**Comment by non-binary** [comment]
Milestone: C: Single Sign On
Link: [milestone#3](#).
Goal: January 1st, 2021.

- [ ] Epic: Implement backend SSO component.
  - [ ] Task: Research Google SSO and how to implement it in Rust.
  - [ ] Task: Implement backend component in Rust.
  - [ ] Task: Write unit tests.
- [ ] Epic: Implement frontend SSO component.
  - [ ] Task: Research Google SSO and how to implement it in the frontend.
  - [ ] Task: Implement frontend component in Swift.
  - [ ] Task: Write unit tests.
  - [ ] Task: Write UI tests.
- [ ] Epic: Access Control Management.
  - [ ] Task: Implement backend component to store active users.
  - [ ] Task: Implement frontend component to show active users.
  - [ ] Task: Implement ability to add new users.
  - [ ] Task: Implement ability to remove existing users.
  - [ ] Task: Implement sessions so when a user is removed, they can no longer use the app.
